version: "2"

services:
  sygal-import-ws:
    container_name: sygal-import-ws-container
    build:
      context: .
      args:
        PHP_VERSION: 7.0
    ports:
     - "8080:80"
     - "8443:443"
    volumes:
     - .:/app
    working_dir: /app
    network_mode: bridge
